### ISSUE TITLE
Why was the MIT license chosen?

### ISSUE THREAD

**Issue by Muller555541** [globaldce/globaldce-gateway#1]
Given that an open, transparent, distributed p2p network is a central element of the globaldce project it seems unusual that it is licensed under the MIT license which allows proprietary closed source derivatives.

[http://en.wikipedia.org/wiki/MIT_License](http://en.wikipedia.org/wiki/MIT_License) 

Does anyone know if there was a stated or expressed reason for not choosing a free software license?

**Comment by EmmettKim93** [comment]
The MIT License is a permissive license that carries very few restrictions. With the MIT license more people will end up using the globaldce gateway implementation.
